// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlqjN5H6FMjeAPH-1QPlwhTJdSJhoCEU',
    appId: '1:269585801774:web:0bc8a829e7d6109e7f35bf',
    messagingSenderId: '269585801774',
    projectId: 'travile-2cd7c',
    authDomain: 'travile-2cd7c.firebaseapp.com',
    storageBucket: 'travile-2cd7c.appspot.com',
    measurementId: 'G-TG5L5ESMS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-LH6duG1GGR4qrFYInPbE5AVOE59zP0M',
    appId: '1:269585801774:android:0833d9e5124179827f35bf',
    messagingSenderId: '269585801774',
    projectId: 'travile-2cd7c',
    storageBucket: 'travile-2cd7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgMLdlE9pfJ4tq-elGCty1ZHseCshS1I',
    appId: '1:269585801774:ios:6f430920f5af4d4f7f35bf',
    messagingSenderId: '269585801774',
    projectId: 'travile-2cd7c',
    storageBucket: 'travile-2cd7c.appspot.com',
    iosClientId: '269585801774-cmdh8cplcq91drnm8hcqmgqb3su3po68.apps.googleusercontent.com',
    iosBundleId: 'com.example.travile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFgMLdlE9pfJ4tq-elGCty1ZHseCshS1I',
    appId: '1:269585801774:ios:6f430920f5af4d4f7f35bf',
    messagingSenderId: '269585801774',
    projectId: 'travile-2cd7c',
    storageBucket: 'travile-2cd7c.appspot.com',
    iosClientId: '269585801774-cmdh8cplcq91drnm8hcqmgqb3su3po68.apps.googleusercontent.com',
    iosBundleId: 'com.example.travile',
  );
}
